version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=""
      - DB_NAME=taskmanagement

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: taskmanagement
    ports:
      - "3306:3306"
